name: Deploy to Preview Channel

on:
  push:
    branches:
      - main
      - dev

env:
  FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
  PROJECT_ID: gaia-capstone06-prd
  GAR_LOCATION: asia-southeast1
  REPOSITORY: cloud-run-source-deploy
  SERVICE: knowva-backend
  REGION: asia-southeast1

jobs:
  build_and_preview:

    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with: 
          credentials_json: '${{ secrets.CLOUDRUN_SERVICE_ACCOUNT }}'
          token_format: 'access_token'

      # Authenticate Docker to Google Cloud Artifact Registry
      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v1'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'

      - name: Build and Push Container
        run: |-
          docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}" ./
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}"

      - name: Deploy to Cloud Run
        id: deploy
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}
          flags: '--allow-unauthenticated --set-cloudsql-instances=${{ vars.CLOUD_SQL_CONNECTION_NAME }}'
          env_vars: |
            POSTGRES_USER= ${{ vars.POSTGRES_USER }}
            POSTGRES_PASSWORD= ${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_DB= ${{ vars.POSTGRES_DB }}
            FIREBASE_API_KEY= ${{ secrets.FIREBASE_API_KEY }}
            CLOUD_SQL_CONNECTION_NAME= ${{ vars.CLOUD_SQL_CONNECTION_NAME }}

      - uses: actions/setup-node@master
      - name: Installing project dependencies
        working-directory: ./frontend
        run: npm install
      - name: Building the project
        working-directory: ./frontend
        run: npm run build

      - run: npm install -g firebase-tools

      - name: 'Authenticate with Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'

      - run: firebase use gaia-capstone06-prd
      - run: firebase deploy --only hosting

      - name: "Installing Python"
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.1

      - name: "Installing Python Dependencies"
        run: pip install -r backend/requirements.txt

      - name: "Run Python Tests"
        run: python -m pytest backend/tests/