name: Deploy Frontend to Firebase
'on':
  push:
    branches:
    - main
env:
  FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
  PROJECT_ID: gaia-capstone06-prd
jobs:
  deploy_frontend:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Installing project dependencies
      working-directory: ./frontend
      run: npm install
    - name: Building the project
      working-directory: ./frontend
      run: npm run build
    - name: Install Firebase CLI
      run: npm install -g firebase-tools
    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
    - name: Deploy to Firebase
      run: firebase use gaia-capstone06-prd && firebase deploy --only hosting
