FROM python:3.12
ENV PYTHONUNBUFFERED True

RUN pip install --upgrade pip
COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r  requirements.txt

ENV APP_HOME /root
WORKDIR $APP_HOME
COPY backend/ $APP_HOME/backend

EXPOSE 8000
WORKDIR $APP_HOME/backend
CMD ["python", "main.py"]
